# Generated by Django 6.0.3 on 2026-03-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voiceprocessingrequest',
            new_name='voice_voice_user_id_bf348b_idx',
            old_name='voice_voicep_user_id_7b8c9d_idx',
        ),
    ]
