# Generated by Django 6.0.3 on 2026-03-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_daily_limit', models.IntegerField(default=1000)),
                ('default_monthly_limit', models.IntegerField(default=30000)),
                ('key_expiry_days', models.IntegerField(default=365)),
                ('require_approval_new_keys', models.BooleanField(default=False)),
                ('approve_threshold', models.IntegerField(default=85)),
                ('reject_threshold', models.IntegerField(default=40)),
                ('auto_approve_high_confidence', models.BooleanField(default=True)),
                ('max_image_size_mb', models.FloatField(default=5.0)),
                ('allowed_image_formats', models.CharField(default='jpg,jpeg,png,webp', max_length=128)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('force_2fa_admin', models.BooleanField(default=False)),
                ('ip_whitelist_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
