# Generated by Django 6.0.3 on 2026-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ethiovoice_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='allowed_audio_formats',
            field=models.CharField(default='wav,mp3,mpeg,webm', help_text='Comma-separated extensions (no dots)', max_length=128),
        ),
    ]
