# Generated by Django 6.0.3 on 2026-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='daily_request_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_request_limit',
            field=models.IntegerField(default=30000),
        ),
    ]
