# Generated by Django 6.0.3 on 2026-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_send_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Successful verification emails sent for the current pending email (max enforced in views).'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_signup_email_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last time the user changed email on the verify page (cooldown between changes).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_username_edit_used',
            field=models.BooleanField(default=False, help_text='After one username change on the verify page, further edits are disabled.'),
        ),
    ]
