# Generated by Django 6.0.3 on 2026-03-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikeylog',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='authentication.apikey'),
        ),
        migrations.AddIndex(
            model_name='apikeylog',
            index=models.Index(fields=['-timestamp'], name='authenticat_timesta_7ce5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeylog',
            index=models.Index(fields=['api_key', '-timestamp'], name='authenticat_api_key_e6990d_idx'),
        ),
    ]
