# Generated by Django 6.0.3 on 2026-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_apikey_key_preview_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiAbuseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_enable', models.BooleanField(default=True, help_text='Master switch for server-side registration checks (except hard admin block).')),
                ('enforce_admin_block', models.BooleanField(default=True, help_text='When off, is_blocked users may still use the site (not recommended).')),
                ('block_disposable_email', models.BooleanField(default=True, help_text='Reject signups whose email domain is on the disposable/temp list.')),
                ('require_gmail_domain_for_password_signup', models.BooleanField(default=False, help_text='If enabled, password registration only allows @gmail.com / @googlemail.com.')),
                ('block_same_ip_registration', models.BooleanField(default=True)),
                ('same_ip_lookback_hours', models.PositiveIntegerField(default=24)),
                ('max_accounts_per_ip_in_lookback', models.PositiveIntegerField(default=1, help_text='Block new password signups when this many accounts already used the same IP in the lookback window.')),
                ('block_same_fingerprint', models.BooleanField(default=True)),
                ('fingerprint_lookback_hours', models.PositiveIntegerField(default=168)),
                ('block_rapid_registration_window', models.BooleanField(default=True, help_text='Block when several registrations occur from the same IP or fingerprint within a short window.')),
                ('rapid_registration_window_minutes', models.PositiveIntegerField(default=10)),
                ('max_registrations_per_ip_in_rapid_window', models.PositiveIntegerField(default=1)),
                ('max_registrations_per_fingerprint_in_rapid_window', models.PositiveIntegerField(default=1)),
                ('device_tracker_cookie_enabled', models.BooleanField(default=True, help_text='Long-lived HttpOnly cookie: block a second account from the same browser profile.')),
                ('device_tracker_cookie_max_age_days', models.PositiveIntegerField(default=400)),
                ('auto_block_ip_on_burst', models.BooleanField(default=True)),
                ('suspicious_burst_registration_count', models.PositiveIntegerField(default=3)),
                ('suspicious_burst_window_minutes', models.PositiveIntegerField(default=60)),
                ('auto_blocked_ip_duration_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anti-abuse settings',
                'verbose_name_plural': 'Anti-abuse settings',
            },
        ),
        migrations.CreateModel(
            name='BlockedIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Empty = use default duration from anti-abuse settings at creation time.', null=True)),
                ('blocked_automatically', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Blocked IP address',
                'verbose_name_plural': 'Blocked IP addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('fingerprint_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email_domain', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('blocked', 'Blocked'), ('success', 'Success'), ('failed_validation', 'Failed validation')], db_index=True, max_length=32)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', '-created_at'], name='authenticat_ip_addr_c7ce14_idx'), models.Index(fields=['fingerprint_hash', '-created_at'], name='authenticat_fingerp_6a924b_idx')],
            },
        ),
    ]
