# Generated by Django 6.0.3 on 2026-03-25 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_antiabuse_and_blocking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationattempt',
            name='browser_family',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='device_class',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='email_input',
            field=models.CharField(blank=True, help_text='Email entered on the form (staff-only audit).', max_length=254),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='fingerprint_preview',
            field=models.CharField(blank=True, help_text='Short fingerprint label for dashboards (not the password).', max_length=220),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='os_family',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_attempt_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='username_input',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='registrationattempt',
            index=models.Index(fields=['device_class', '-created_at'], name='authenticat_device__62ddb9_idx'),
        ),
    ]
