# Generated by Django 6.0.3 on 2026-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_antiabuse_oauth_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiabusesettings',
            name='oauth_signup_antiabuse_enabled',
            field=models.BooleanField(default=True, help_text='When on, new Google OAuth sign-ups use the same registration limits (IP, fingerprint, disposable email, rapid window, device cookie). Existing Google users are unaffected.'),
        ),
        migrations.AlterField(
            model_name='registrationattempt',
            name='outcome',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('success', 'Success'), ('failed_validation', 'Failed validation'), ('pending_verification', 'Pending email verification')], db_index=True, max_length=32),
        ),
    ]
